#https://github.com/pal-robotics/pal_navigation_cfg_public/blob/master/pal_navigation_cfg_tiago/config/base/common/global_costmap_plugins_public_sim.yaml
# Independent settings for the planner's costmap
global_costmap:
  # attention, the order and combination method matters
  plugins:
    - name: static_layer
      type: 'costmap_2d::StaticLayer'
    - name: obstacle_laser_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'