#https://github.com/pal-robotics/pal_navigation_cfg_public/blob/master/pal_navigation_cfg_tiago/config/base/common/local_costmap_plugins_public_sim.yaml
# Independent settings for the local costmap
local_costmap:
  # attention, the order and combination method matters
  plugins:
    - name: obstacle_laser_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: obstacle_sonar_layer
      type: 'range_sensor_layer::RangeSensorLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'