version: '2.4'
services:
  tiago-sim:
    container_name: ros-tiago-sim
    image: tiago-sim:noetic
    runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
      WAIT_FOR_ROSCORE: 0
      ROS_IP: $ROS_IP
      ROS_HOSTNAME: $ROS_HOSTNAME
      ROS_MASTER_URI: $ROS_MASTER_URI
      QT_X11_NO_MITSHM: '1'
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
    network_mode: host
    privileged: true
    stdin_open: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - ../../config:/config
    command: #TODO add custom launch file :)
      - bash
      - -c
      - |
        source /opt/ros/noetic/setup.bash
        source /root/catkin_ws/devel/setup.bash
        roslaunch tiago_gazebo tiago_gazebo.launch public_sim:=true end_effector:=pal-gripper gzpose:="-x -1.0 -y -4.5 -z 0.0 -R 0.0 -P 0.0 -Y 1.57" &
        rosrun ros_object_map_server main.py --frame_path /maps/robocup_2023/frames --object_path /maps/robocup_2023/objects &
        rosrun rviz rviz -d /config/rviz_config.rviz &
        rosrun look_to_point look_to_point &
        sleep 10
        rosservice call /object_map_server/spawn_gazebo "{}" 
        tail -f /dev/null