version: '2.4'
services:
  tiago-sim:
    container_name: ros-tiago-sim
    image: tiago-sim:noetic
    runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
      WAIT_FOR_ROSCORE: 1
      ROS_IP: $ROS_IP
      ROS_HOSTNAME: $ROS_HOSTNAME
      ROS_MASTER_URI: $ROS_MASTER_URI
      QT_X11_NO_MITSHM: '1'
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
    network_mode: host
    privileged: true
    stdin_open: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
    command: roslaunch tiago_gazebo tiago_gazebo.launch public_sim:=true end_effector:=pal-gripper
