version: '2.4'
services:
  tiago-sim:
    container_name: tiago-sim
    image: tiago-sim:noetic
    runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
      WAIT_FOR_ROSCORE: 0
      ROS_IP: $ROS_IP
      ROS_HOSTNAME: $ROS_HOSTNAME
      ROS_MASTER_URI: $ROS_MASTER_URI
      QT_X11_NO_MITSHM: '1'
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
    network_mode: host
    privileged: true
    stdin_open: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - ../tiago_sim:/root/catkin_ws/src/tiago_sim
    command: roslaunch tiago_sim tiago_sim.launch gzpose:="-x -1.0 -y -4.5 -z 0.0 -R 0.0 -P 0.0 -Y 1.57"