#https://github.com/pal-robotics/pal_navigation_cfg_public/blob/master/pal_navigation_cfg_tiago/config/base/common/recovery_behaviors.yaml
recovery_behaviors:
  - name: 'costmap_reset_far'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'costmap_reset_close'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'

costmap_reset_far:
  reset_distance: 3.0
  layer_names: ["obstacle_laser_layer"]

costmap_reset_close:
  reset_distance: 1.5
  layer_names: ["obstacle_laser_layer"]